#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M3{1,0,4.8,4
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g.dep
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g.dep: ;
endif

package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g: | .interfaces
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g: package/package_ti.runtime.wiring.cc26xx.tests.alan.c lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.sm3g: | .interfaces
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.sm3g: package/package_ti.runtime.wiring.cc26xx.tests.alan.c lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/main.om3g.dep
package/lib/lib/sketches/main.om3g.dep: ;
endif

package/lib/lib/sketches/main.om3g: | .interfaces
package/lib/lib/sketches/main.om3g: main.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/main.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/main.sm3g: | .interfaces
package/lib/lib/sketches/main.sm3g: main.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/main.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/GLCDI2C.om3g.dep
package/lib/lib/sketches/GLCDI2C.om3g.dep: ;
endif

package/lib/lib/sketches/GLCDI2C.om3g: | .interfaces
package/lib/lib/sketches/GLCDI2C.om3g: GLCDI2C.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/GLCDI2C.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/GLCDI2C.sm3g: | .interfaces
package/lib/lib/sketches/GLCDI2C.sm3g: GLCDI2C.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/GLCDI2C.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/monitor1.om3g.dep
package/lib/lib/sketches/monitor1.om3g.dep: ;
endif

package/lib/lib/sketches/monitor1.om3g: | .interfaces
package/lib/lib/sketches/monitor1.om3g: monitor1.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor1.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/monitor1.sm3g: | .interfaces
package/lib/lib/sketches/monitor1.sm3g: monitor1.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor1.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/monitor.om3g.dep
package/lib/lib/sketches/monitor.om3g.dep: ;
endif

package/lib/lib/sketches/monitor.om3g: | .interfaces
package/lib/lib/sketches/monitor.om3g: monitor.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/monitor.sm3g: | .interfaces
package/lib/lib/sketches/monitor.sm3g: monitor.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/monitor.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch0.om3g.dep
package/lib/lib/sketches/sketch0.om3g.dep: ;
endif

package/lib/lib/sketches/sketch0.om3g: | .interfaces
package/lib/lib/sketches/sketch0.om3g: sketch0.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch0.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch0.sm3g: | .interfaces
package/lib/lib/sketches/sketch0.sm3g: sketch0.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch0.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch1.om3g.dep
package/lib/lib/sketches/sketch1.om3g.dep: ;
endif

package/lib/lib/sketches/sketch1.om3g: | .interfaces
package/lib/lib/sketches/sketch1.om3g: sketch1.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch1.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch1.sm3g: | .interfaces
package/lib/lib/sketches/sketch1.sm3g: sketch1.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch1.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch2.om3g.dep
package/lib/lib/sketches/sketch2.om3g.dep: ;
endif

package/lib/lib/sketches/sketch2.om3g: | .interfaces
package/lib/lib/sketches/sketch2.om3g: sketch2.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch2.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch2.sm3g: | .interfaces
package/lib/lib/sketches/sketch2.sm3g: sketch2.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch2.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch3.om3g.dep
package/lib/lib/sketches/sketch3.om3g.dep: ;
endif

package/lib/lib/sketches/sketch3.om3g: | .interfaces
package/lib/lib/sketches/sketch3.om3g: sketch3.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch3.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch3.sm3g: | .interfaces
package/lib/lib/sketches/sketch3.sm3g: sketch3.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch3.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch4.om3g.dep
package/lib/lib/sketches/sketch4.om3g.dep: ;
endif

package/lib/lib/sketches/sketch4.om3g: | .interfaces
package/lib/lib/sketches/sketch4.om3g: sketch4.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch4.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch4.sm3g: | .interfaces
package/lib/lib/sketches/sketch4.sm3g: sketch4.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch4.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch5.om3g.dep
package/lib/lib/sketches/sketch5.om3g.dep: ;
endif

package/lib/lib/sketches/sketch5.om3g: | .interfaces
package/lib/lib/sketches/sketch5.om3g: sketch5.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch5.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch5.sm3g: | .interfaces
package/lib/lib/sketches/sketch5.sm3g: sketch5.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch5.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch6.om3g.dep
package/lib/lib/sketches/sketch6.om3g.dep: ;
endif

package/lib/lib/sketches/sketch6.om3g: | .interfaces
package/lib/lib/sketches/sketch6.om3g: sketch6.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch6.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch6.sm3g: | .interfaces
package/lib/lib/sketches/sketch6.sm3g: sketch6.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch6.sm3g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/sketches/sketch7.om3g.dep
package/lib/lib/sketches/sketch7.om3g.dep: ;
endif

package/lib/lib/sketches/sketch7.om3g: | .interfaces
package/lib/lib/sketches/sketch7.om3g: sketch7.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti -I/db/vtree/library/trees/avalaprod/avalaprod-q08/exports/bios_6_42_00_08/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include   $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch7.om3g: export LD_LIBRARY_PATH=

package/lib/lib/sketches/sketch7.sm3g: | .interfaces
package/lib/lib/sketches/sketch7.sm3g: sketch7.cpp lib/sketches.am3g.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) cppm3g -S $< ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c++ -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m3 -mthumb -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -gdwarf-3 -gstrict-dwarf -fno-exceptions -Dxdc__nolocalstring=1 -DBOARD_CC2650STK_BLE -Dxdc_target_name__=M3 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_4_8_4  -Os  -fno-rtti  $(XDCINCS)  -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/sketches/sketch7.sm3g: export LD_LIBRARY_PATH=

clean,m3g ::
	-$(RM) package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g
	-$(RM) package/lib/lib/sketches/main.om3g
	-$(RM) package/lib/lib/sketches/GLCDI2C.om3g
	-$(RM) package/lib/lib/sketches/monitor1.om3g
	-$(RM) package/lib/lib/sketches/monitor.om3g
	-$(RM) package/lib/lib/sketches/sketch0.om3g
	-$(RM) package/lib/lib/sketches/sketch1.om3g
	-$(RM) package/lib/lib/sketches/sketch2.om3g
	-$(RM) package/lib/lib/sketches/sketch3.om3g
	-$(RM) package/lib/lib/sketches/sketch4.om3g
	-$(RM) package/lib/lib/sketches/sketch5.om3g
	-$(RM) package/lib/lib/sketches/sketch6.om3g
	-$(RM) package/lib/lib/sketches/sketch7.om3g
	-$(RM) package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.sm3g
	-$(RM) package/lib/lib/sketches/main.sm3g
	-$(RM) package/lib/lib/sketches/GLCDI2C.sm3g
	-$(RM) package/lib/lib/sketches/monitor1.sm3g
	-$(RM) package/lib/lib/sketches/monitor.sm3g
	-$(RM) package/lib/lib/sketches/sketch0.sm3g
	-$(RM) package/lib/lib/sketches/sketch1.sm3g
	-$(RM) package/lib/lib/sketches/sketch2.sm3g
	-$(RM) package/lib/lib/sketches/sketch3.sm3g
	-$(RM) package/lib/lib/sketches/sketch4.sm3g
	-$(RM) package/lib/lib/sketches/sketch5.sm3g
	-$(RM) package/lib/lib/sketches/sketch6.sm3g
	-$(RM) package/lib/lib/sketches/sketch7.sm3g

lib/sketches.am3g: package/lib/lib/sketches/package/package_ti.runtime.wiring.cc26xx.tests.alan.om3g package/lib/lib/sketches/main.om3g package/lib/lib/sketches/GLCDI2C.om3g package/lib/lib/sketches/monitor1.om3g package/lib/lib/sketches/monitor.om3g package/lib/lib/sketches/sketch0.om3g package/lib/lib/sketches/sketch1.om3g package/lib/lib/sketches/sketch2.om3g package/lib/lib/sketches/sketch3.om3g package/lib/lib/sketches/sketch4.om3g package/lib/lib/sketches/sketch5.om3g package/lib/lib/sketches/sketch6.om3g package/lib/lib/sketches/sketch7.om3g lib/sketches.am3g.mak

clean::
	-$(RM) lib/sketches.am3g.mak
