PROGNAME = zumo
VARIANT  = RedBearLab_CC3200
SOURCES  = main.cpp \
           L3G.cpp LSM303.cpp ZumoMotors.cpp \
           apLoop.cpp imuLoop.ino motorLoop.cpp

include ../common.mak

# build flash image
all: $(PROGNAME).bin
